version: "3"

tasks:
  init:
    description: init repo
    cmds:
      - task: init:pre-commit
      - task: install

  install:
    description: Install dependencies
    cmds:
      - uv sync

  init:pre-commit:
    description: Install pre-commit hooks
    cmds:
      - uv add pre-commit --dev
      - uv run pre-commit install --hook-type commit-msg
